// react/generator/src/App.js
import React, {useState} from 'react';
import uniqid from 'uniqid';
import './App.css';
import {getRandomPart} from "./utils";

const generators = {
    generator1: {
        part1: ["G1part1.1", "G1part1.2", "G1part1.3"],
            part2: ["G1part2.1", "G1part2.2", "G1part2.3"],
            part3: ["G1part3.1", "G1part3.2", "G1part3.3"],
    },
    generator2: {
        part1: ["G2part1.1", "G2part1.2", "G2part1.3"],
            part2: ["G2part2.1", "G2part2.2", "G2part2.3"],
            part3: ["G2part3.1", "G2part3.2", "G2part3.3"],
    }
};

const Citations = ({ citations }) => {

    return <ul>
        {citations.map(c => <li key={c.id}>{c.value}</li>)}
    </ul>

}

const App = () => {

    const [generator, setGenerator] = useState('generator1');
    const [nbCitations, setNbCitations] = useState(1);
    const [citations, setCitations] = useState([]);

    const handleSubmit = (e) => {
        e.preventDefault()

        const _citations = []
        for(let i = 0; i < nbCitations; i++){
            const c = {
                id: uniqid(),
                value: `${getRandomPart(generators, generator, 'part1')} ${getRandomPart(generators, generator, 'part2')} ${getRandomPart(generators, generator, 'part3')}`
            }
            _citations.push(c)
        }
        setCitations(_citations);
    }


    return (
        <div>

            <form onSubmit={handleSubmit}>

                <div>
                    <label htmlFor="generator1">Générateur 1</label>
                    <input
                        id="generator1"
                        name="catgeory"
                        type="radio"
                        value="generator1"
                        onChange={() => setGenerator('generator1')}
                    />

                    <label htmlFor="generator2">Générateur 2</label>
                    <input
                        id="generator2"
                        name="catgeory"
                        type="radio"
                        value="generator2"
                        onChange={() => setGenerator('generator2')}
                    />
                </div>

                <div>
                    <label>Nb de citations</label>
                    <select
                        name="nbCitations"
                        onChange={e => setNbCitations(parseInt(e.target.value))}
                    >
                        <option value={1}>1</option>
                        <option value={2}>2</option>
                        <option value={3}>3</option>
                        <option value={4}>4</option>
                        <option value={5}>5</option>
                    </select>
                </div>

                <button type="submit">Générer</button>


            </form>

            <Citations
                citations={citations}
            />
        </div>
    );
}

export default App;

// angular/generator/src/app/app.component.ts
import {Component} from '@angular/core';
import {getRandomPart} from "../utils";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'generators';
  citations: Array<Object> = [];

  generators = {
    generator1: {
      part1: ["G1part1.1", "G1part1.2", "G1part1.3"],
      part2: ["G1part2.1", "G1part2.2", "G1part2.3"],
      part3: ["G1part3.1", "G1part3.2", "G1part3.3"],
    },
    generator2: {
      part1: ["G2part1.1", "G2part1.2", "G2part1.3"],
      part2: ["G2part2.1", "G2part2.2", "G2part2.3"],
      part3: ["G2part3.1", "G2part3.2", "G2part3.3"],
    }
  };

  submit(e) {
    e.preventDefault()
    const generator = e.target.categorie.value
    const nbCitations = parseInt(e.target.nbCitations.value)
    this.citations = [];
    for (let i = 0; i < nbCitations; i++) {
      const citation = {
        value: `${getRandomPart(this.generators, generator, 'part1')} ${getRandomPart(this.generators, generator, 'part2')} ${getRandomPart(this.generators, generator, 'part3')}`
      };
      this.citations.push(citation);
    }
  }
}

<h1>Générateur</h1>


<form
  name="form"
  (submit)="submit($event)"
>
  <div class="row">
    <div class="col-lg-6 col-md-12 radios" style="text-align: center; margin-bottom: 5px;">
      <div class="radio">
        <input type="radio" name="categorie" value="generator1" id="type1">
        <label for="type1">type1</label>
      </div>
      <div class="radio">
        <input type="radio" name="categorie" value="generator2" id="type2">
        <label for="type2">type2</label>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col-lg-4 col-md-12 radios" style="text-align: center; margin-bottom: 5px;">
      <div class="radio">
        <input type="radio" name="nbCitations" value="1" id="1">
        <label for="1">Un</label>
      </div>
      <div class="radio">
        <input type="radio" name="nbCitations" value="2" id="2">
        <label for="2">Deux</label>
      </div>
      <div class="radio">
        <input type="radio" name="nbCitations" value="3" id="3">
        <label for="3">Trois</label>
      </div>
      <div class="radio">
        <input type="radio" name="nbCitations" value="4" id="4">
        <label for="4">Quatre</label>
      </div>
      <div class="radio">
        <input type="radio" name="nbCitations" value="5" id="5">
        <label for="5">Cinq</label>
      </div>
    </div>

    <button id="generate">Générer</button>

    <ul>
      <li *ngFor="let citation of citations">
        {{citation.value}}
      </li>
    </ul>

  </div>
</form>
